name: Workflow2

on: [push, pull_request, workflow_call, workflow_call]

jobs:
  spellcheck:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"
