name: Install HWLOC via Vcpkg (run-vcpkg)

on: 
  workflow_dispatch: # This allows the workflow to be triggered manually.

jobs:
  build:
    runs-on: windows-latest # Specifies that the job runs on the latest Windows runner.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
     
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.22.6

    - name: Initialize vcpkg
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
        vcpkgDirectory: ${{ github.workspace }}/build/vcpkg
        vcpkgConfigurationJsonGlob: '**/vcpkg-configuration.json'

    - name: Install dependencies
      run: |
        vcpkg install
      shell: pwsh # Specifies PowerShell as the shell for running the script.
